[package]
name = "arc_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
bench = false

[dependencies]
image = "0.24.3"
imageproc = "0.23.0"
# bencher = "0.1.5"
criterion = { version = "0.3.5", features = ["html_reports"] }

[profile.release]
debug = 1

[[bench]]
name = "arc_bench"
harness = false
