[package]
name = "arc_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
bench = false

[dependencies]
image = "0.24.3"
imageproc = "0.23.0"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
env_logger = "0.9.0"
log = "0.4.17"

[profile.release]
debug = 1

[[bench]]
name = "arc_bench"
harness = false
